language: swift
osx_image: xcode13.1

cache:
  bundler: true
  cocoapods: true

xcode_workspace: Trimer.xcworkspace
xcode_scheme: TrimerTests
xcode_destination: platform=iOS Simulator,OS=15.0,name=iPhone 12
