language: swift
osx_image: xcode13.1
xcode_project: Trimer.xcodeproj # path to your xcodeproj folder
xcode_scheme: TrimerTests
xcode_destination: platform=iOS Simulator,OS=10.1,name=iPad Pro (9.7-inch)
